version: 0.2
phases:
  install:
    runtime-versions:
      dotnet: 2.2
  pre_build: 
    commands: 
      - echo Logging in to Amazon ECR... 
      - $(aws ecr get-login --no-include-email --region us-east-1) 
  build: 
    commands: 
      - echo Build started on `date` 
      - echo Building the Docker image... 
      - docker build -t leavewebapp:latest ./LeaveWebApp/
      - docker tag leavewebapp:latest  831210339789.dkr.ecr.us-east-1.amazonaws.com/leavewebapp:071019 
  post_build: 
    commands: 
      - echo Build completed on `date` 
      - echo Pushing the Docker image... 
      - docker push 831210339789.dkr.ecr.us-east-1.amazonaws.com/leavewebapp:071019 